#!/usr/bin/env python3
"""build_menu — render data/menu.json into index.html.

Why a generator instead of fetching the JSON in the browser: a restaurant menu
is the single most searched part of a restaurant site, so it has to exist in
the HTML that a crawler and a no-JavaScript visitor receive. Keeping the JSON
as the only place prices are edited gives us both — one source of truth, and
static markup.

Run after every edit to data/menu.json:
    python3 tools/build_menu.py
"""
import html
import json
import re
import sys

DATA = "data/menu.json"
PAGE = "index.html"
START = "<!-- MENU:START"
END = "<!-- MENU:END -->"


def esc(s):
    return html.escape(s or "", quote=True)


def render(menu):
    cur = esc(menu.get("currency", ""))
    out = []

    out.append('      <div class="filters" role="group" aria-label="تصفية المنيو">')
    out.append('        <button class="filter" type="button" data-filter="all" '
               'aria-pressed="true">الكل</button>')
    for c in menu["categories"]:
        out.append(f'        <button class="filter" type="button" '
                   f'data-filter="{esc(c["id"])}" aria-pressed="false">'
                   f'{esc(c["ar"])}</button>')
    out.append("      </div>")

    out.append('      <ul class="grid grid--3">')
    for it in menu["items"]:
        price = it.get("price")
        if price is None:
            price_html = ('<span class="todo">السعر في انتظار البيانات</span>')
        else:
            price_html = f'{esc(str(price))} <span>{cur}</span>'

        out.append(f'        <li class="card" data-category="{esc(it["category"])}"'
                   f'{" data-featured" if it.get("featured") else ""} data-reveal>')
        out.append(f'          <h3>{esc(it["ar"])}</h3>')
        if it.get("en"):
            out.append(f'          <p class="lat">{esc(it["en"])}</p>')
        if it.get("desc"):
            out.append(f'          <p>{esc(it["desc"])}</p>')
        out.append(f'          <p class="card__price">{price_html}</p>')
        out.append("        </li>")
    out.append("      </ul>")

    return "\n".join(out)


def main():
    with open(DATA, encoding="utf-8") as fh:
        menu = json.load(fh)
    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()

    pattern = re.compile(
        re.escape(START) + r".*?-->(.*?)" + re.escape(END),
        re.DOTALL,
    )
    if not pattern.search(page):
        print(f"markers {START} ... {END} not found in {PAGE}", file=sys.stderr)
        return 2

    block = render(menu)
    header = (f"{START} — generated by tools/build_menu.py from {DATA}.\n"
              "           Do not hand-edit: edit the JSON and re-run the script. -->")
    page = pattern.sub(lambda m: f"{header}\n{block}\n      {END}", page, count=1)

    with open(PAGE, "w", encoding="utf-8") as fh:
        fh.write(page)

    missing = sum(1 for i in menu["items"] if i.get("price") is None)
    print(f"rendered {len(menu['items'])} items "
          f"across {len(menu['categories'])} categories")
    if missing:
        print(f"note: {missing} items still have no price", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
